@E-Commerce.API_HostAddress = https://localhost:7032


GET {{E-Commerce.API_HostAddress}}/api/product

###

GET {{E-Commerce.API_HostAddress}}/api/product/3

###






PUT {{E-Commerce.API_HostAddress}}/api/product/8
Content-Type: application/json

{
  "name": "Integral Calculus",
  "description": "Comprehensive guide covering calculus, linear algebra, and differential equations.",
  "price":4000.99,
  "stockQuantity": 75,
  "productCategories": [
    { "categoryId": 2 }
  ]
}

###


PUT {{E-Commerce.API_HostAddress}}/api/product/100
Content-Type: application/json

{
  "id": 10,
  "name": "Integral Calculus",
  "description": "Comprehensive guide covering calculus, linear algebra, and differential equations.",
  "price":4000.99,
  "stockQuantity": 75,
  "productCategories": [
    { "categoryId": 2 }
  ]
}

###

DELETE {{E-Commerce.API_HostAddress}}/api/product/7

###

POST {{E-Commerce.API_HostAddress}}/api/product
Content-Type: application/json

{
    "name": "Advanced Integrals",
    "description": "Comprehensive guide covering calculus, linear algebra, and differential equations.",
    "price": 4000.99,
    "stockQuantity": 75,
    "productCategories": [
      { "categoryId": 2 }
    ]
  
}

###

DELETE {{E-Commerce.API_HostAddress}}/api/product/9

###

GET {{E-Commerce.API_HostAddress}}/api/category

###

GET {{E-Commerce.API_HostAddress}}/api/category/5

###

POST {{E-Commerce.API_HostAddress}}/api/category
Content-Type: application/json

{    
    "name": "Health",
    "description": "wellness products"
}

###

PUT {{E-Commerce.API_HostAddress}}/api/category/7
Content-Type: application/json

{
    "id": 7,
    "name": "Health",
    "description": "personal care and wellness products"
}

###

DELETE {{E-Commerce.API_HostAddress}}/api/category/6

###


GET {{E-Commerce.API_HostAddress}}/api/orderitem

###


GET {{E-Commerce.API_HostAddress}}/api/order/2

###








###

POST {{E-Commerce.API_HostAddress}}/api/order
Content-Type: application/json

{
  "customerName": "Joy Ng",
  "orderDate": "2025-02-07T00:00:00",
  "orderItem": [
    {
      "productId": 3,
      "quantity": 12,
      "unitPrice": 19.99
    },
    {
      "productId": 2,
      "quantity": 10,
      "unitPrice": 1299.99
    }
  ]
}




###



GET {{E-Commerce.API_HostAddress}}/api/order/11

###

GET {{E-Commerce.API_HostAddress}}/api/order

###



PUT {{E-Commerce.API_HostAddress}}/api/order/19
Content-Type: application/json

{
  "id": 19,
  "customerName": "Joy Gonzaga",
  "orderDate": "2025-02-07",
  "orderItem": [
    {
      "id": 1, 
      "orderId": 19,
      "productId": 3,
      "quantity": 12,
      "unitPrice": 20.00
    },
    {
      "id": 2,
      "orderId": 19,
      "productId": 2,
      "quantity": 10,
      "unitPrice": 1300.99
    }
  ]
}
###




DELETE {{E-Commerce.API_HostAddress}}/api/order/19

###
